on:
  push :
    branches:
      - preprod
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: access871187812.webspace-data.io
          username: u104722386
          password: planeat2021
          server-dir: preprod.planeat-france.com/